CREATE database IF NOT EXISTS EjercicioMer01;

CREATE table IF NOT EXISTS EMPLEADO (
   NUMERO_LEGAJO int NOT NULL,
   DNI int NOT NULL,
   APELLIDO varchar(30) NOT NULL,
   NOMBRE varchar(30) NOT NULL, 
   SUELDO int NOT NULL, 
   primary key(NUMERO_LEGAJO), 
   CONSTRAINT fk_EMPLEADO
   foreign key(DNI)
);

INSERT INTO EMPLEADO(NUMERO_LEGAJO,DNI,APELLIDO,NOMBRE,SUELDO)
VALUES (4548,33902312,"VILLALBA","LEANDRO",4588);

CREATE TABLE IF NOT EXISTS ADMINISTRATIVO(
   TIPOEMPLEADO varchar(15),
   NUM_LEGAJO_ADMIN int NOT NULL, 
   PRIMARY KEY(NUM_LEGAJO_ADMIN),
   CONSTRAINT fk_ADMINISTRATIVO_EMPLEADO
   FOREIGN KEY(NUM_LEGAJO_ADMIN) REFERENCES EMPLEADO(NUMERO_LEGAJO)
);

CREATE TABLE IF NOT EXISTS DOCTOR(
  ID_ESPECIALIDAD INT NOT NULL,
  ESPECIALIDAD VARCHAR(40) NOT NULL,
  ID_DOCTOR INT NOT NULL,
  PRIMARY KEY(ID_ESPECIALIDAD), 
  CONSTRAINT FK_DOCTOR_EMPLEADO FOREIGN KEY(ID_DOCTOR) REFERENCES EMPLEADO(NUMERO_LEGAJO)
);


DROP TABLE DOCTOR;
DROP TABLE ADMINISTRATIVO;

CREATE TABLE IF NOT EXISTS ADMINISTRATIVO(
  TIPOEMPLEADO varchar(15),
   NUM_LEGAJO_ADMIN int NOT NULL, 
   PRIMARY KEY(NUM_LEGAJO_ADMIN),
   CONSTRAINT fk_ADMINISTRATIVO_EMPLEADO
   FOREIGN KEY(NUM_LEGAJO_ADMIN) REFERENCES EMPLEADO(NUMERO_LEGAJO)
);

INSERT INTO ADMINISTRATIVO(NUM_LEGAJO_ADMIN, TIPOEMPLEADO)
VALUES (45145, "ADMINISTRATIVO");

DROP TABLE ADMINISTRATIVO;

DROP TABLE EMPLEADO;
/*-----------------------------------------------------------------------------------------*/

CREATE table IF NOT EXISTS EMPLEADO (
   NUMERO_LEGAJO int NOT NULL,
   DNI int NOT NULL,
   APELLIDO varchar(30) NOT NULL,
   NOMBRE varchar(30) NOT NULL, 
   SUELDO int NOT NULL, 
   primary key(NUMERO_LEGAJO),
   CONSTRAINT fk_EMPLEADO
   foreign key(DNI) REFERENCES empleado (NUMERO_LEGAJO)
);

alter table empleado drop foreign key fk_EMPLEADO;

INSERT INTO EMPLEADO(NUMERO_LEGAJO, DNI, APELLIDO, NOMBRE,SUELDO) 
VALUES (123456, 33902312, "Villalba", "Leandro", 40000);

ALTER TABLE empleado add PUESTO varchar(20);
ALTER TABLE empleado drop PUESTO;
ALTER TABLE empleado add PUESTO INT NOT NULL;

UPDATE EMPLEADO SET PUESTO=1 WHERE NUMERO_LEGAJO=123456;

SELECT * FROM EMPLEADO;

CREATE TABLE IF NOT EXISTS ADMINISTRATIVO(
   ID_PUESTO INT NOT NULL,
   DESCRIPCION VARCHAR (20), 
   primary key(ID_PUESTO)
);

INSERT INTO ADMINISTRATIVO(ID_PUESTO, DESCRIPCION) 
VALUES (1, "administrativo");
INSERT INTO ADMINISTRATIVO(ID_PUESTO, DESCRIPCION) 
VALUES (2, "DOCTOR");


ALTER TABLE EMPLEADO ADD FOREIGN KEY (puesto) REFERENCES administrativo(id_puesto);

SELECT NUMERO_LEGAJO,DNI, NOMBRE, APELLIDO, DESCRIPCION,ID_PUESTO FROM empleado AS emp JOIN administrativo as adm on emp.PUESTO = adm.ID_PUESTO WHERE PUESTO=2;

INSERT INTO empleado(numero_legajo, dni, apellido, nombre, puesto, sueldo)
values (45874, 33951656, "CALVI", "ALEJO", 2,985945); 

update empleado set nombre="Andres" where NUMERO_LEGAJO=123456;

SELECT * FROM EMPLEADO where puesto=2;