create database if not exists EjerNorm2;

create table if not exists UBICACION(
  ID_UBICACION INT NOT NULL,
  NOMBRE_PROVINCIA varchar(20),
  PRIMARY KEY (ID_UBICACION)
);

create table if not exists CIUDAD(
  ID_CODIGOCIUDAD INT NOT NULL,
  NOMBRE_CIUDAD VARCHAR(30),
  COD_PROVINCIA INT NOT NULL, 
  PRIMARY KEY (ID_CODIGOCIUDAD),
  constraint fk_CIUDAD_UBICACION
  foreign key (COD_PROVINCIA) REFERENCES ubicacion(ID_UBICACION)
);

INSERT INTO UBICACION(ID_UBICACION, NOMBRE_PROVINCIA)
VALUES (1, "BUENOS AIRES");
INSERT INTO UBICACION(ID_UBICACION, NOMBRE_PROVINCIA)
VALUES (2, "SANTA FE");
INSERT INTO UBICACION(ID_UBICACION, NOMBRE_PROVINCIA)
VALUES (3, "CORDOBA");

INSERT INTO CIUDAD(ID_CODIGOCIUDAD, NOMBRE_CIUDAD, COD_PROVINCIA)
VALUES(12, "LA PLATA",1);
INSERT INTO CIUDAD(ID_CODIGOCIUDAD, NOMBRE_CIUDAD, COD_PROVINCIA)
VALUES(345, "SAN NICOLAS",1);
INSERT INTO CIUDAD(ID_CODIGOCIUDAD, NOMBRE_CIUDAD, COD_PROVINCIA)
VALUES(47, "ROSARIO",2);
INSERT INTO CIUDAD(ID_CODIGOCIUDAD, NOMBRE_CIUDAD, COD_PROVINCIA)
VALUES(19, "VILLA CARLOS PAZ",3);

SELECT ID_CODIGOCIUDAD,NOMBRE_CIUDAD, NOMBRE_PROVINCIA FROM ubicacion AS UB INNER JOIN CIUDAD AS CIU ON UB.ID_UBICACION = CIU.COD_PROVINCIA ORDER BY ID_CODIGOCIUDAD ASC;


